FAQ ready! [DO NOT MERGE]
ScratchAddons/website pull request #72
Opened 2020-11-28 14:01 UTC by Hans5958

Okay, here it is, the Frequently Asked Questions page is ready, at least for me.

You can check the current rev on [here](https://github.com/ScratchAddons/website/blob/faq/site/faq.md). Please leave a review about it, and suggest final changes if there is.

**Do not merge this in an instant!** I repeat, **do not merge!** Let me merge it by myself.

Resolves #32.

2020-11-28 16:10 UTC, WorldLanguages commented on site/faq.md
> +Most times you turned on addons that utilise the so-called "traps" on the process. These addons often include a warning, so turn those off and try again. The warnings are look like this.
Outdated. Right now I'd recommend users who feel slowdowns to open a discussion or send feedback on where exactly they feel the slowdown. This has happened in the past, for example, someone reported laggy block moving in the editor, and we ended up finding the cause and fixing it in v1.4.0. Was not related to traps at all.

2020-11-28 16:10 UTC, WorldLanguages commented on site/faq.md
> +If you have a mid-end computer, chances are the performance won't be dropped significantly, unless if you turned on addons that utilise "traps". Otherwise, it will just be a major change. Feel free t
Outdated.

2020-11-28 16:11 UTC, WorldLanguages requested changes
Looks good, except we don't use traps anymore. It's *a* trap now, just for the VM, and it's removed after the VM is trapped :P

2020-11-28 16:55 UTC, Hans5958 commented
> 
> 
> Looks good, except we don't use traps anymore. It's _a_ trap now, just for the VM, and it's removed after the VM is trapped :P

Not sure about how this new thing work, so please tell me what sentence should I put there.

2020-11-28 17:26 UTC, WorldLanguages commented
@Hans5958 I'd just remove those 2 questions.

2020-11-29 02:54 UTC, Hans5958 commented
I'll just keep the question and decrease (or remove) the mentions of the traps. Keep in mind there are people who have low-end computers that they even get lagged when running two apps at the same time.

2020-11-29 05:14 UTC, Hans5958 commented
Alright, fixed it. Any other comments?

2020-11-29 15:56 UTC, WorldLanguages commented
> I'll just keep the question and decrease (or remove) the mentions of the traps. Keep in mind there are people who have low-end computers that they even get lagged when running two apps at the same time.

I'm aware, but the CPU and RAM use of the extension is insignificant to those used by the browser and the Scratch player/editor.

2020-11-29 16:42 UTC, Hans5958 commented
@WorldLanguages Have you checked the latest one?

2020-11-29 18:30 UTC, WorldLanguages approved these changes
Changes look good

2020-12-01 08:42 UTC, Hans5958 commented
Okay, no other comments, it seems. Launch time.

2020-12-01 08:42 UTC, merged

2020-12-01 15:56 UTC, WorldLanguages commented
lol the fact you merged something with [DO NOT MERGE] in its title :P

2020-12-02 02:53 UTC, Hans5958 commented
> 
> 
> lol the fact you merged something with [DO NOT MERGE] in its title :P

It's just a warning for you guys who wanted to merge by themselves